## DataFrame

In [4]:
import pandas as pd

In [5]:
data = pd.DataFrame({
    "Name": ["Ali", "Ehmad"],
    "Lemonades": [1, 4],  
})
data

    Name  Lemonades
0    Ali          1
1  Ehmad          4

In [6]:
s1 = pd.Series(data=[1,2,3,4,5])
s2 = pd.Series(data=[10,20,30,40,50])

# si = pd.Series(data=[100,200,300,400,500], index=list('abcde'))

# data = pd.DataFrame({'C1': s1, 'C2': s2, 'C3': si})
data = pd.DataFrame({'C1': s1, 'C2': s2})
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

### Attributes

In [7]:
print(s1.shape)
print(data.shape)

print(data.columns)
print(data.dtypes)

(5,)
(5, 2)
Index(['C1', 'C2'], dtype='str')
C1    int64
C2    int64
dtype: object

### Accessing Data

In [8]:
# Using labels

# loc
# data.loc['a']
print(data.loc[1])  
print(data.loc[1, 'C1']) # you can mention column name here

# iloc
print(data.iloc[1])
print(data.iloc[2, 1])  # you can mention column's index here

C1     2
C2    20
Name: 1, dtype: int64
2
C1     2
C2    20
Name: 1, dtype: int64
30

### Methods

In [ ]:
# head()
# tail()
# count()

# info()
data.info() # details

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   C1      5 non-null      int64
 1   C2      5 non-null      int64
dtypes: int64(2)
memory usage: 212.0 bytes

In [63]:
# describe()
data.describe() # describe

             C1         C2
count  5.000000   5.000000
mean   3.000000  30.000000
std    1.581139  15.811388
min    1.000000  10.000000
25%    2.000000  20.000000
50%    3.000000  30.000000
75%    4.000000  40.000000
max    5.000000  50.000000

In [64]:
# mean()
data.mean()

C1     3.0
C2    30.0
dtype: float64

### Filtering

In [71]:
# print(data['C1'] > 3)
data[data['C1'] > 3]

   C1  C2
3   4  40
4   5  50

### Adding, Updating, Deleting

In [96]:
# Adding

data['Tips'] = [1,2,3,4, None]
data

   C1  C2  Tips
0   1  10   1.0
1   2  20   2.0
2   3  30   3.0
3   4  40   4.0
4   5  50   NaN

In [ ]:
# Deleting

# del
del data["C1"]
data

# drop
data = data.drop(columns='Tips')
data

   C1  C2
0   1  10
1   2  20
2   3  30
3   4  40
4   5  50

In [9]:
# Update

# print(data['C1'] == 10)

data.loc[data['C1'] == 3] = 10
data

   C1  C2
0   1  10
1   2  20
2  10  10
3   4  40
4   5  50

In [14]:
# Rename

# data.rename(columns={'C1': 'Column1'})  # Temp

data.rename(columns={'C1': 'Column1'}, inplace=True)
data

         C2
Column1
1        10
2        20
10       10
4        40
5        50

### Index and Selection

In [15]:
# Using a column as index

data.set_index('Column1', inplace=True)

KeyError: "None of ['Column1'] are in the columns"

In [16]:
data

         C2
Column1
1        10
2        20
10       10
4        40
5        50

In [17]:
data.loc[10, 'C2']

np.int64(10)

In [19]:
data['Tips'] = ['a', 'b', 'c', 'd', 'e']
data

         C2 Tips
Column1
1        10    a
2        20    b
10       10    c
4        40    d
5        50    e

In [20]:
data.set_index('Tips', inplace=True)
data

      C2
Tips
a     10
b     20
c     10
d     40
e     50

In [27]:
data.loc['d', 'C2']

np.int64(40)

# Multi Index

In [34]:
# multi_index = pd.DataFrame({
#     'Alphas': ['a', 'b', 'c', 'd', 'e'],
#     "Ints": [6,7,8,9,10], 
#     'Floats': [1.25, 2.25, 5.2, 1, 4]
# })
# multi_index.set_index(['Ints', 'Alphas'], inplace=True)

multi_index = pd.DataFrame({
    'Alphas': ['a', 'b', 'c', 'd', 'e'],
    "Ints": [6,7,8,9,10], 
    'Floats': [1.25, 2.25, 5.2, 1, 4]
}).set_index(['Ints', 'Alphas'])
multi_index

             Floats
Ints Alphas
6    a         1.25
7    b         2.25
8    c         5.20
9    d         1.00
10   e         4.00

### Selecting with conditions

In [42]:
value = 3
print(multi_index['Floats'] > value)

print(multi_index[multi_index['Floats'] > value])

Ints  Alphas
6     a         False
7     b         False
8     c          True
9     d         False
10    e          True
Name: Floats, dtype: bool
             Floats
Ints Alphas
8    c          5.2
10   e          4.0

### Query method 
#### does the same thing without calling the var twice

In [45]:
multi_index.query('Floats > 2')

             Floats
Ints Alphas
7    b         2.25
8    c         5.20
10   e         4.00